name: Python Testing
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
        
    - name: Run tests
      run: |
        python -m unittest
